server:
    port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:root@127.0.0.1:9001/eureka/
      
spring:
  application:
    name: backstage-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    url: jdbc:mysql://134.175.90.151:3306/product_v1?useUnicode=true&characterEncoding=UTF8&useSSL=FALSE&allowMultiQueries=true
    username: root
    password: Hlxd@123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2: 
      min-idle: 5 
      initial-size: 5 
      max-total: 5 
      max-wait-millis: 200

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.hlxd.microcloud.entity,com.hlxd.microcloud.entity.vo
  global-config:
    db-column-underline: true
    refresh-mapper: true
        
logging:
  level:
    com.hlxd.backstage.mapper: debug
